name: Build and push Go application to cloud run

inputs:
  buildContext:
    description: 'Path to the directory containing the application source code. Defaults to the current directory if none specified.'
    required: true
  dockerfilePath:
    description: 'Path to the Dockerfile for the application'
    required: true
  imageName:
    description: 'Name of the image created in the artifact registry'
    required: true

runs:
  using: "composite"
  steps:
  - id: 'auth'
    uses: 'google-github-actions/auth@v0'
    with:
      credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
  - run: |-
      gcloud --quiet auth configure-docker ${{ secrets.REGISTRY_BASE_URL }}
  - name: Build and push container image to registry
    uses: docker/build-push-action@v2
    with:
      push: true
      tags: ${{ secrets.REGISTRY_BASE_URL }}/${{ secrets.PROJECT_ID}}/${{secrets.REGISTRY_NAME}}/${{ inputs.imageName }}:${{ github.sha }}
      context: ${{ inputs.buildContext }}
      file: ${{ inputs.dockerfilePath }}

  - id: deploy
    uses: google-github-actions/deploy-cloudrun@v0
    with:
      service: ${{ secrets.ORG_SERVICE_NAME }}
      image: ${{ secrets.REGISTRY_BASE_URL }}/${{ secrets.PROJECT_ID}}/${{secrets.REGISTRY_NAME}}/${{ inputs.imageName }}:${{ github.sha }}
      region: ${{ secrets.ORG_SERVICE_REGION }}
