// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/orgs/": {
            "get": {
                "security": [
                    {
                        "ClientCredentials": []
                    }
                ],
                "description": "Org retrieval is permitted through the use of scopes. For scope definitions go to https://bcc-code.github.io/projects/bcc-membership-docs/data-structures-and-scopes.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "orgs"
                ],
                "summary": "Find orgs",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/Org"
                            }
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ClientCredentials": []
                    }
                ],
                "description": "Org updating is permitted through the use of scopes. For scope definitions go to https://bcc-code.github.io/projects/bcc-membership-docs/data-structures-and-scopes.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "orgs"
                ],
                "summary": "Update org",
                "parameters": [
                    {
                        "description": "Org create reuqest",
                        "name": "org",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Org"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Org"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ClientCredentials": []
                    }
                ],
                "description": "Org creation is permitted through the use of scopes. For scope definitions go to https://bcc-code.github.io/projects/bcc-membership-docs/data-structures-and-scopes.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "orgs"
                ],
                "summary": "Create org",
                "parameters": [
                    {
                        "description": "Org create reuqest",
                        "name": "org",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Org"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Org"
                        }
                    }
                }
            }
        },
        "/orgs/{orgID}": {
            "get": {
                "security": [
                    {
                        "ClientCredentials": []
                    }
                ],
                "description": "Org retrieval is permitted through the use of scopes. For scope definitions go to https://bcc-code.github.io/projects/bcc-membership-docs/data-structures-and-scopes.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "orgs"
                ],
                "summary": "Get org by orgID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "orgID",
                        "name": "orgID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Org"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "Address": {
            "type": "object",
            "properties": {
                "street1": {
                    "type": "string",
                    "x-order": "1"
                },
                "street2": {
                    "type": "string",
                    "x-order": "2"
                },
                "city": {
                    "type": "string",
                    "x-order": "3"
                },
                "region": {
                    "type": "string",
                    "x-order": "4"
                },
                "countryIso2Code": {
                    "type": "string",
                    "x-order": "5"
                },
                "postalCode": {
                    "type": "string",
                    "x-order": "6"
                },
                "countryName": {
                    "type": "string",
                    "x-order": "7"
                },
                "countryNameNative": {
                    "type": "string",
                    "x-order": "8"
                }
            }
        },
        "Org": {
            "type": "object",
            "properties": {
                "orgID": {
                    "type": "integer",
                    "x-order": "1"
                },
                "name": {
                    "type": "string",
                    "x-order": "2"
                },
                "legalName": {
                    "type": "string",
                    "x-order": "3"
                },
                "type": {
                    "type": "string",
                    "x-order": "4"
                },
                "visitingAddress": {
                    "x-order": "5",
                    "$ref": "#/definitions/Address"
                },
                "postalAddress": {
                    "x-order": "6",
                    "$ref": "#/definitions/Address"
                },
                "billingAddress": {
                    "x-order": "7",
                    "$ref": "#/definitions/Address"
                }
            }
        }
    },
    "securityDefinitions": {
        "ClientCredentials": {
            "type": "oauth2",
            "flow": "application",
            "tokenUrl": "/docs/token",
            "scopes": {
                "org#read": " read orgs",
                "org#write": " modify orgs"
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "BCC Orgs API",
	Description:      "This is the Orgs API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
