apiVersion: v1
kind: Service
metadata:
    name: "bccplatformdev-e306"
    labels:
        app: "bccplatformdev-e306"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "bccplatformdev-e306"