name: 'Set environment variables'
description: 'Configures environment variables for a workflow'
inputs:
  googleCredentials:
    description: 'Google credentials in JSON format'
    required: true
  dbInstance:
    description: 'Database instance name'
    required: true

runs:
  using: "composite"
  steps:
    - uses: mattes/gce-cloudsql-proxy-action@v1
      with:
        creds: ${{ inputs.googleCredentials }}
        instance: ${{ inputs.dbInstance }}