name: Build and push Go application to cloud run
description: 'Deploys a new cloud run revision'

inputs:
  projectId:
    description: 'Google project ID'
    required: true
  buildContext:
    description: 'Path to the directory containing the application source code. Defaults to the current directory if none specified.'
    required: true
  dockerfilePath:
    description: 'Path to the Dockerfile for the application'
    required: true
  imageName:
    description: 'Name of the image created in the artifact registry'
    required: true
  googleCredentials:
    description: 'Google credentials in JSON'
    required: true
  registryBaseUrl:
    description: 'Base URL of the artifact registry'
    required: true
  registryName:
    description: 'Name of the artifact registry'
    required: true
  serviceName:
    description: 'Name of the cloud run service'
    required: true
  serviceLocation:
    description: 'Location of the cloud run service'
    required: true

runs:
  using: "composite"
  steps:
  - id: 'auth'
    uses: 'google-github-actions/auth@v0'
    with:
      credentials_json: '${{ inputs.googleCredentials }}'
  - run: |-
      gcloud --quiet auth configure-docker ${{ inputs.registryBaseUrl }}
    shell: bash
  - name: Build and push container image to registry
    uses: docker/build-push-action@v2
    with:
      push: true
      tags: ${{ inputs.registryBaseUrl }}/${{ inputs.projectId}}/${{inputs.registryName}}/${{ inputs.imageName }}:${{ github.sha }}
      context: ${{ inputs.buildContext }}
      file: ${{ inputs.dockerfilePath }}

  - id: deploy
    uses: google-github-actions/deploy-cloudrun@v0
    with:
      service: ${{ inputs.serviceName }}
      image: ${{ inputs.registryBaseUrl }}/${{ inputs.projectId}}/${{inputs.registryName}}/${{ inputs.imageName }}:${{ github.sha }}
      region: ${{ inputs.serviceRegion }}
