version: '3.1'

services:
  #################
  # Application   #
  #################
  person_app:
    ports:
      - "4000:4000"
    env_file: ../.env
    build: 
      context: ../
      dockerfile: devops/Dockerfile