version: '3.1'

services:
  orgs_api_test:
    build: 
      context: ../
      dockerfile: devops/test.Dockerfile
    image: orgs_api_test
    container_name: orgs_api_test
    ports:
      - "4000:4000"
    volumes:
      - ../src:/app/src
      - ../db/migrations/:/db/migrations
      - ../db/test-data/:/db/test-data
      - ./docker-scripts/:/scripts
    tty: true
    env_file: ../.env.example
    environment:
      - AUTH0_ISSUER=${AUTH0_ISSUER}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
    entrypoint: "/scripts/run-tests.sh"
    depends_on:
      - "orgs_db"

  orgs_db:
    image: postgres:13.6-alpine
    ports:
      - "5432:5432"
    env_file: ../.env.example
    container_name: orgs_db
    restart: always
