version: '3.1'

services:
  orgs_api:
    ports:
      - "4000:4000"
    volumes:
      - ../src:/app/src
      - ../db/migrations/:/db/migrations
      - ../db/test-data/:/db/test-data
      - ./docker-scripts/:/scripts
    command: ["/scripts/wait-for-orgs-db.sh", "--", "air"]
    env_file: ../.env.example
    environment:
      - AUTH0_ISSUER=${AUTH0_ISSUER}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
    container_name: orgs_api
    build: 
      context: ../
      dockerfile: devops/dev.Dockerfile
    depends_on:
      - "orgs_db"

  orgs_db:
    image: postgres:13.6-alpine
    ports:
      - "5432:5432"
    env_file: ../.env
    container_name: orgs_db
    restart: always
