name: 'Set environment variables'
description: 'Configures environment variables for a workflow'
inputs:
  googleCredentials:
    description: 'Google credentials in JSON format'
    required: true
  dbInstance:
    description: 'Database instance name'
    required: true
  dbName:
    description: 'Database name'
    required: true
  dbUsername:
    description: 'Database username'
    required: true
  dbPassword:
    description: 'Database password'
    required: true

runs:
  using: "composite"
  steps:
    - uses: mattes/gce-cloudsql-proxy-action@v1
      with:
        creds: ${{ inputs.googleCredentials }}
        instance: ${{ inputs.dbInstance }}
    - uses: actions/setup-go@v3
      with:
        go-version: '>=1.17.0'
    - run: go install -tags "nomymysql nomysql nosqlite3" github.com/pressly/goose/v3/cmd/goose@latest
      shell: bash
    - run: goose -dir bcc-orgs/db/migrations -table schema_migrations postgres "user=${{ inputs.dbUsername }} password=${{ inputs.dbPassword }} dbname=${{ inputs.dbName }} sslmode=disable" up 
      shell: bash

