name: Build and push Go application to cloud run
description: 'Deploys a new cloud run revision'

inputs:
  projectId:
    description: 'Google project ID'
    required: true
  buildContext:
    description: 'Path to the directory containing the application source code. Defaults to the current directory if none specified.'
    required: true
  dockerfilePath:
    description: 'Path to the Dockerfile for the application'
    required: true
  imageName:
    description: 'Name of the image created in the artifact registry'
    required: true
  googleCredentials:
    description: 'Google credentials in JSON'
    required: true
  registryBaseUrl:
    description: 'Base URL of the artifact registry'
    required: true
  registryName:
    description: 'Name of the artifact registry'
    required: true

runs:
  using: "composite"
  steps:
  - id: 'auth'
    uses: 'google-github-actions/auth@v0'
    with:
      credentials_json: '${{ inputs.googleCredentials }}'
  - name: Set up Docker Buildx
    id: buildx
    uses: docker/setup-buildx-action@master

  - name: Login to the artifact registry
    shell: bash
    run: |-
      gcloud --quiet auth configure-docker ${{ inputs.registryBaseUrl }}

  - name: Cache Docker layers
    uses: actions/cache@v2
    with:
      path: /tmp/.buildx-cache
      key: ${{ runner.os }}-buildx-${{ github.sha }}
      restore-keys: |
        ${{ runner.os }}-buildx
  - name: Build and push container image to registry
    uses: docker/build-push-action@v2
    with:
      push: true
      tags: ${{ inputs.registryBaseUrl }}/${{ inputs.projectId}}/${{inputs.registryName}}/${{ inputs.imageName }}:${{ github.sha }}
      context: ${{ inputs.buildContext }}
      file: ${{ inputs.dockerfilePath }}
      cache-from: type=local,src=/tmp/.buildx-cache
      cache-to: type=local,dest=/tmp/.buildx-cache-new

  - name: Move cache
    shell: bash
    run: |
      rm -rf /tmp/.buildx-cache
      mv /tmp/.buildx-cache-new /tmp/.buildx-cache

