name: NuGet Tenants.Contracts

on:
  push:
    branches: [ master ]
    paths:
      - "bcc-tenants/**"
      - ".github/workflows/nuget-tenant-contracts.yml"
    
  pull_request:
    branches: [ master ]
    paths:
      - "bcc-tenants/**"
      - ".github/workflows/nuget-tenant-contracts.yml"

  workflow_dispatch:

env:
  API_KEY: ${{ secrets.NUGET_API_KEY }}
  CSPROJ_PATH: bcc-tenants/Bcc.Tenants.Contracts/Bcc.Tenants.Contracts.csproj
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
           dotnet-version: 6.0.*
           
      - name: Set Environment Variables
        uses: ./.github/actions/setvars
        with:
          varFilePath: ./.github/variables/version.env
          
      - name: Set package version
        run: |
          if [[ $GITHUB_REF == 'refs/heads/master' && $GITHUB_EVENT_NAME == 'push' ]]; then
            echo "VERSION=${{ env.BCC_TENANTS_VERSION_MAIN }}.${{ github.run_number}}" >> "$GITHUB_ENV"
          else
            echo "VERSION=${{ env.BCC_TENANTS_VERSION_MAIN }}.${{ github.run_number}}-beta" >> "$GITHUB_ENV"
          fi

      - name: Run Tests
        run: dotnet test ${{ env.CSPROJ_PATH }}

      - name: Package
        run: dotnet pack -p:PackageVersion=${{ env.VERSION }} -c Release -o . ${{ env.CSPROJ_PATH }}

      - name: Publish
        run: dotnet nuget push *.nupkg -k ${{env.API_KEY}} -s https://api.nuget.org/v3/index.json
