@audience={{$dotenv AUTH0_AUDIENCE}}
@auth0Host={{$dotenv AUTH0_ISSUER}}
@clientID={{$dotenv AUTH0_CLIENT_ID}}
@clientSecret={{$dotenv AUTH0_CLIENT_SECRET}}
@localHost=http://localhost:{{$dotenv PORT}}

# @name getCredentials
POST {{auth0Host}}/oauth/token HTTP/1.1
content-type: application/json

{
    "audience": "{{audience}}",
    "grant_type": "client_credentials",
    "client_id": "{{clientID}}",
    "client_secret": "{{clientSecret}}",
    "scope": "read:org write:org"
}

###
@token = Bearer {{getCredentials.response.body.access_token}}

# @name getOrg
GET {{localHost}}/orgs/1 HTTP/1.1
Authorization: {{token}}

###

# @name getOrgs
GET {{localHost}}/orgs HTTP/1.1
Authorization: {{token}}

###

# @name createOrg
POST {{localHost}}/orgs HTTP/1.1
Authorization: {{token}}

{
    "name": "Terwolde",
    "type": "Church"
}

###

# @name updateOrg
PUT {{localHost}}/orgs/1 HTTP/1.1
content-type: application/json
Authorization: {{token}}

{
    "name": "TEST",
    "visitingAddress": {
        "street1": "Veien1"
    }
}

